# Generated by Django 5.2.17 on 2026-10-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guards', '0002_guard_updated_at_guarddocument_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='wage_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='guard',
            name='wage_type',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('HOURLY', 'Hourly')], default='DAILY', max_length=20),
        ),
    ]
