# Generated by Django 5.2.17 on 2026-10-03 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guards', '0001_initial'),
        ('locations', '0001_initial'),
        ('schedules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('SUPERVISOR_AVAILABLE', 'Is a supervisor available?'), ('RELIEF_BREAK', 'Need relief / break'), ('BACKUP', 'Need backup (non-emergency)'), ('EQUIPMENT_SITE_ISSUE', 'Equipment or site issue'), ('SCHEDULE_QUERY', 'Schedule query'), ('OTHER', 'Other')], max_length=30)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REPLIED', 'Replied'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('response_option', models.CharField(blank=True, choices=[('ON_MY_WAY', 'On my way'), ('PLEASE_WAIT', 'Please wait'), ('APPROVED', 'Approved'), ('CALL_ME', 'Call me'), ('DECLINED', 'Declined')], default='', max_length=20)),
                ('response_note', models.CharField(blank=True, default='', max_length=200)),
                ('eta_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guard_requests', to='guards.guard')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_guard_requests', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guard_requests', to='locations.location')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guard_requests', to='schedules.dutyschedule')),
            ],
            options={
                'db_table': 'guard_requests',
                'indexes': [models.Index(fields=['location', 'status'], name='guard_reque_locatio_7eda52_idx')],
            },
        ),
    ]
