# Generated by Django 5.2.17 on 2026-10-03 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guards', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='guards.guard')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='locations.location')),
            ],
            options={
                'db_table': 'duty_schedules',
                'indexes': [models.Index(fields=['guard', 'shift_start', 'shift_end'], name='duty_schedu_guard_i_e19287_idx')],
            },
        ),
    ]
