# Generated by Django 5.2.17 on 2026-10-03 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guards', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent')], default='ABSENT', max_length=20)),
                ('check_in_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='guards.guard')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_record', to='schedules.dutyschedule')),
            ],
            options={
                'verbose_name_plural': 'attendance records',
                'db_table': 'attendance',
                'indexes': [models.Index(fields=['guard', 'schedule'], name='attendance_guard_i_e7a8e4_idx')],
            },
        ),
    ]
