# Generated by Django 5.2.17 on 2026-10-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
